# Generated by Django 4.2.29 on 2026-03-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('min_threshold', models.IntegerField(default=0)),
                ('max_threshold', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('LOW', 'Low Stock'), ('NORMAL', 'Normal'), ('HIGH', 'Overstock')], default='NORMAL', editable=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-updated_at'],
            },
        ),
    ]
